// projects/react-no-ts/src/components/Blog.jsx
// Copyright (c) 2025 Bytedance Ltd. and/or its affiliates
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import React from 'react'
import { useDelete } from '../hooks/useDelete'
import { useEdit } from '../hooks/useEdit'
import useMarkdown from '../hooks/useMarkdown'
import BlogForm from './BlogForm'
import Comments from './Comments'
import TruncatedTitle from './TruncatedTitle'

function Blog({ title, detail }) {
  const handleDelete = useDelete();
  const { isEditFormVisible, setIsEditFormVisible, handleEdit } = useEdit();
  const { convertMarkdown } = useMarkdown();

  return (
    <div style={{ position: 'relative' }}>
      <button
        className="delete-btn"
        onClick={handleDelete}
        style={{
          position: 'absolute',
          top: '0',
          right: '100px',
          backgroundColor: '#ff4d4d',
          color: 'white',
          border: 'none',
          padding: '8px 16px',
          borderRadius: '4px',
          cursor: 'pointer',
          fontWeight: 'bold',
          transition: 'background-color 0.3s ease'
        }}
        onMouseEnter={(e) => {
          e.target.style.backgroundColor = '#ff3333'
        }}
        onMouseLeave={(e) => {
          e.target.style.backgroundColor = '#ff4d4d'
        }}
      >
        Delete
      </button>
      <button
        className="edit-btn"
        onClick={() => setIsEditFormVisible(true)}
        style={{
          position: 'absolute',
          top: '0',
          right: '0',
          backgroundColor: '#4A90E2',
          color: 'white',
          border: 'none',
          padding: '8px 16px',
          borderRadius: '4px',
          cursor: 'pointer',
          fontWeight: 'bold',
          transition: 'background-color 0.3s ease'
        }}
        onMouseEnter={(e) => {
          e.target.style.backgroundColor = '#357ABD'
        }}
        onMouseLeave={(e) => {
          e.target.style.backgroundColor = '#4A90E2'
        }}
      >
        Edit
      </button>
      <h2 className="blog-title" style={{
        width: 'fit-content',
        fontSize: '24px'
      }}>
        <TruncatedTitle title={title} />
      </h2>
      <div 
        className="markdown-content"
        dangerouslySetInnerHTML={{ __html: convertMarkdown(detail) }}
        style={{
          lineHeight: '1.6',
          '& code': {
            backgroundColor: '#f5f5f5',
            padding: '2px 4px',
            borderRadius: '4px',
            fontSize: '0.9em'
          },
          '& pre': {
            backgroundColor: '#f5f5f5',
            padding: '1em',
            borderRadius: '4px',
            overflowX: 'auto'
          },
          '& img': {
            maxWidth: '100%',
            height: 'auto'
          },
          '& a': {
            color: '#4A90E2',
            textDecoration: 'none'
          },
          '& a:hover': {
            textDecoration: 'underline'
          }
        }}
      />
      <BlogForm 
        isVisible={isEditFormVisible}
        onClose={() => setIsEditFormVisible(false)}
        isEdit={true}
        initialTitle={title}
        initialDetail={detail}
        onEdit={handleEdit}
      />
      <Comments blogTitle={title} />
    </div>
  )
}

export default Blog

// projects/vue/src/components/Blog.vue
<!-- 
Copyright (c) 2025 Bytedance Ltd. and/or its affiliates

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 -->

<template>
  <div class="blog">
    <div class="blog-actions">
      <button class="delete-btn" @click="deleteBlog">Delete</button>
      <button class="edit-btn" @click="editBlog">Edit</button>
    </div>
    <h1 class="blog-title">
      <TruncatedTitle :title="title" />
    </h1>
    <div v-html="markdownToHtml(detail)"></div>
    <Comments />
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { useDelete } from '../composables/useDelete';
import { useEdit } from '../composables/useEdit';
import Comments from './Comments.vue';
import { markdownToHtml } from '../composables/useMarkdown';
import TruncatedTitle from './TruncatedTitle.vue';

export default defineComponent({
  components: {
    Comments,
    TruncatedTitle
  },
  props: {
    title: String,
    detail: String
  },
  setup(props, { emit }) {
    const { deleteBlog } = useDelete();
    const { editBlog } = useEdit();

    return { 
      deleteBlog, 
      editBlog: () => editBlog(),
      markdownToHtml
    };
  }
});
</script>

<style scoped>
.blog {
  position: relative;
  padding: 20px;
  border: 1px solid #e0e0e0;
  border-radius: 8px;
  flex: 1;
}

.blog-actions {
  position: absolute;
  top: 10px;
  right: 10px;
}

.blog-title {
  font-size: 24px;
  max-width: 300px;
  width: fit-content;
}

.delete-btn, .edit-btn {
  margin-left: 10px;
  padding: 5px 10px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

.delete-btn {
  background-color: #f44336;
  color: white;
}

.edit-btn {
  background-color: #2196F3;
  color: white;
}
</style>
