// projects/angular/src/components/blog-form/blog-form.component.ts
// Copyright (c) 2025 Bytedance Ltd. and/or its affiliates
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import { Component, Output, EventEmitter, inject } from '@angular/core'
import { FormsModule } from '@angular/forms'
import { NgIf } from '@angular/common'
import { BlogService } from '../../services/blog.service'
import { Subscription } from 'rxjs'

@Component({
  selector: 'app-blog-form',
  standalone: true,
  imports: [FormsModule, NgIf],
  template: `
    <div class="modal" [class.visible]="visible">
      <div class="modal-content">
        <span class="visible-count">{{ visibleCount }}</span>
        <button class="close-btn" (click)="onClose()">×</button>
        <h2>{{ isEditing ? 'Edit Blog' : 'Create Blog' }}</h2>
        <form class="form" (submit)="onSubmit($event)">
          <div class="form-group">
            <label for="title">Title:</label>
            <input
              id="title"
              type="text"
              [(ngModel)]="title"
              name="title"
              required
              (ngModelChange)="onTitleChange()"
            />
            <span *ngIf="titleExists" class="error">Title already exists!</span>
          </div>
          <div class="form-group">
            <label for="detail">Detail:</label>
            <textarea id="detail" [(ngModel)]="detail" name="detail" required></textarea>
          </div>
          <button type="submit" class="submit-btn" [disabled]="titleExists">
            {{ isEditing ? 'Update' : 'Create' }}
          </button>
        </form>
      </div>
    </div>
  `,
  styles: `
    .modal {
      position: fixed;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      background: rgba(0,0,0,0.5);
      display: none;
      justify-content: center;
      align-items: center;
      z-index: 1000;
    }
    
    .modal.visible {
      display: flex;
    }

    .modal-content {
      background: white;
      padding: 2rem;
      border-radius: 8px;
      position: relative;
      width: 400px;
      box-shadow: 0 2px 10px rgba(0,0,0,0.1);
    }

    .close-btn {
      position: absolute;
      top: 10px;
      right: 10px;
      border: none;
      background: none;
      font-size: 24px;
      cursor: pointer;
      color: #666;
    }

    .close-btn:hover {
      color: #333;
    }

    .visible-count {
      position: absolute;
      top: 10px;
      left: 10px;
      color: #666;
    }

    h2 {
      margin-top: 0;
      color: #333;
    }

    .form-group {
      margin-bottom: 1rem;
    }

    label {
      display: block;
      margin-bottom: 0.5rem;
      color: #555;
    }

    input, textarea {
      width: 100%;
      padding: 0.5rem;
      border: 1px solid #ddd;
      border-radius: 4px;
      box-sizing: border-box;
    }

    textarea {
      height: 100px;
      resize: vertical;
    }

    .submit-btn {
      background: #4CAF50;
      color: white;
      border: none;
      padding: 0.5rem 1rem;
      border-radius: 4px;
      cursor: pointer;
      width: 100%;
    }

    .submit-btn:disabled {
      background: #cccccc;
      cursor: not-allowed;
    }

    .submit-btn:hover:not(:disabled) {
      background: #45a049;
    }

    .error {
      color: red;
      font-size: 0.8rem;
      margin-top: 0.2rem;
    }
  `,
})
export class BlogFormComponent {
  private blogService = inject(BlogService)

  subscription = new Subscription()

  ngOnInit() {
    this.subscription.add(
      this.blogService.editingBlog$.subscribe((blog) => {
        if (blog) {
          this.showEdit(blog)
        } else {
          this.hide()
        }
      })
    )
  }

  ngOnDestroy() {
    this.subscription.unsubscribe()
  }

  visible = false
  title = ''
  detail = ''
  visibleCount = 0
  titleExists = false
  isEditing = false
  originalTitle = ''

  @Output() close = new EventEmitter<void>()

  show() {
    this.visible = true
    this.visibleCount++
    this.isEditing = false
  }

  showEdit(blog: { title: string; detail: string }) {
    this.visible = true
    this.visibleCount++
    this.isEditing = true
    this.title = blog.title
    this.detail = blog.detail
    this.originalTitle = blog.title
  }

  hide() {
    this.visible = false
    this.title = ''
    this.detail = ''
    this.titleExists = false
    this.isEditing = false
    this.originalTitle = ''
  }

  onClose() {
    this.hide()
    this.close.emit()
  }

  onTitleChange() {
    let blogs = this.blogService.getBlogs()

    if (this.isEditing) {
      blogs = blogs.filter((blog) => blog.title !== this.originalTitle)
    }

    this.titleExists = blogs.some((blog) => blog.title === this.title)
  }

  onSubmit(event: Event) {
    event.preventDefault()
    if (this.title && this.detail) {
      if (this.isEditing) {
        this.blogService.updateBlog(this.originalTitle, { title: this.title, detail: this.detail })
      } else if (!this.titleExists) {
        this.blogService.addBlog({ title: this.title, detail: this.detail })
      }
      this.hide()
    }
  }
}

// projects/svelte/src/components/BlogForm.svelte
<!-- 
Copyright (c) 2025 Bytedance Ltd. and/or its affiliates

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 -->

<script lang="ts">
  import { onMount } from 'svelte';
  import { blogs, selectedBlog } from '../stores/blogStore';
  import { comments } from '../stores/commentStore';
  import { parseMarkdown } from '../utils/markdown';
  import { toast } from '../utils/toast';
  
  export let visible: boolean = false;
  export let onClose: () => void;
  export let editMode: boolean = false;
  export let initialTitle: string = '';
  export let initialDetail: string = '';

  let title = initialTitle;
  let detail = initialDetail;
  let visibleCount = 0;
  let titleError = '';
  let previewMode = false;

  $: parsedDetail = parseMarkdown(detail);

  onMount(() => {
    if (visible) {
      visibleCount++;
    }
  });

  $: if (visible) {
    visibleCount++;
    if (editMode) {
      title = initialTitle;
      detail = initialDetail;
    } else {
      title = '';
      detail = '';
    }
    previewMode = false;
  }

  function checkTitleDuplication(title: string): boolean {
    const editTitle = editMode ? initialTitle : '';
    return $blogs.some(blog => blog.title.toLowerCase() === title.toLowerCase() && blog.title !== editTitle);
  }

  function handleSubmit() {
    if (checkTitleDuplication(title)) {
      titleError = 'This title already exists';
      return; 
    }

    titleError = '';
    const newBlog = { title, detail };
    
    if (editMode) {
      blogs.updateBlog(initialTitle, newBlog);
      comments.updateBlogTitle(initialTitle, title);
      selectedBlog.set(newBlog);
    } else {
      blogs.addBlog(newBlog);
      selectedBlog.set(newBlog);
      toast.showToast('New Blog Created Successfully!');
    }
    
    title = '';
    detail = '';
    onClose();
  }
</script>

{#if visible}
<div class="modal-overlay">
  <div class="modal">
    <div class="visible-count">{visibleCount}</div>
    <button class="close-btn" on:click={onClose}>×</button>
    <h2>{editMode ? 'Edit Blog' : 'Create Blog'}</h2>
    
    <form on:submit|preventDefault={handleSubmit}>
      <div class="form-group">
        <label for="title">Title</label>
        <input 
          id="title"
          type="text" 
          bind:value={title}
          placeholder="Enter title"
          required
        />
        {#if titleError}
          <span class="error">{titleError}</span>
        {/if}
      </div>

      <div class="form-group">
        <label for="detail">
          Detail
          <button 
            type="button" 
            class="preview-toggle" 
            on:click={() => previewMode = !previewMode}
          >
            {previewMode ? 'Edit' : 'Preview'}
          </button>
        </label>
        
        {#if previewMode}
          <div class="preview-content">
            {@html parsedDetail}
          </div>
        {:else}
          <textarea
            id="detail"
            bind:value={detail}
            placeholder="Enter detail (Markdown supported)"
            required
          />
        {/if}
      </div>

      <button type="submit" class="submit-btn">{editMode ? 'Update' : 'Create'}</button>
    </form>
  </div>
</div>
{/if}


<style>
  .modal-overlay {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background: rgba(0, 0, 0, 0.5);
    display: flex;
    justify-content: center;
    align-items: center;
    z-index: 1000;
  }

  .modal {
    background: white;
    padding: 2rem;
    border-radius: 8px;
    width: 90%;
    max-width: 500px;
    position: relative;
  }

  .visible-count {
    position: absolute;
    top: 1rem;
    left: 1rem;
    font-size: 0.875rem;
    color: #666;
  }

  .close-btn {
    position: absolute;
    top: 1rem;
    right: 1rem;
    background: none;
    border: none;
    font-size: 1.5rem;
    cursor: pointer;
    padding: 0;
    width: 30px;
    height: 30px;
    display: flex;
    align-items: center;
    justify-content: center;
    border-radius: 50%;
    transition: background-color 0.2s;
  }

  .close-btn:hover {
    background-color: #f5f5f5;
  }

  h2 {
    margin-top: 0;
    margin-bottom: 1.5rem;
  }

  .form-group {
    margin-bottom: 1rem;
  }

  label {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 0.5rem;
    font-weight: 500;
  }

  input, textarea {
    width: 100%;
    padding: 0.5rem;
    border: 1px solid #ddd;
    border-radius: 4px;
    font-size: 1rem;
  }

  textarea {
    height: 150px;
    resize: vertical;
    font-family: monospace;
  }

  .preview-toggle {
    background: none;
    border: none;
    color: #007bff;
    cursor: pointer;
    padding: 0;
    font-size: 0.875rem;
  }

  .preview-toggle:hover {
    text-decoration: underline;
  }

  .preview-content {
    min-height: 150px;
    padding: 0.5rem;
    border: 1px solid #ddd;
    border-radius: 4px;
    background-color: #f8f9fa;
    overflow-y: auto;
  }

  .error {
    color: red;
    font-size: 0.875rem;
    margin-top: 0.25rem;
    display: block;
  }

  .submit-btn {
    background-color: #4CAF50;
    color: white;
    padding: 0.5rem 1rem;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    font-size: 1rem;
    width: 100%;
    margin-top: 1rem;
  }

  .submit-btn:hover {
    background-color: #45a049;
  }

  .preview-content :global(h1) {
    font-size: 2em;
    margin: 0.67em 0;
  }

  .preview-content :global(h2) {
    font-size: 1.5em;
    margin: 0.83em 0;
  }

  .preview-content :global(h3) {
    font-size: 1.17em;
    margin: 1em 0;
  }

  .preview-content :global(p) {
    margin: 1em 0;
  }

  .preview-content :global(ul) {
    margin: 1em 0;
    padding-left: 40px;
  }

  .preview-content :global(code) {
    background-color: #f5f5f5;
    padding: 0.2em 0.4em;
    border-radius: 3px;
    font-family: monospace;
  }

  .preview-content :global(a) {
    color: #007bff;
    text-decoration: none;
  }

  .preview-content :global(a:hover) {
    text-decoration: underline;
  }
</style>
