// projects/vue/src/components/Blog.vue
<!-- 
Copyright (c) 2025 Bytedance Ltd. and/or its affiliates

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 -->

<template>
  <div class="blog">
    <div class="blog-actions">
      <button class="delete-btn" @click="deleteBlog">Delete</button>
      <button class="edit-btn" @click="editBlog">Edit</button>
    </div>
    <h1 class="blog-title">
      <TruncatedTitle :title="title" />
    </h1>
    <div v-html="markdownToHtml(detail)"></div>
    <Comments />
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { useDelete } from '../composables/useDelete';
import { useEdit } from '../composables/useEdit';
import Comments from './Comments.vue';
import { markdownToHtml } from '../composables/useMarkdown';
import TruncatedTitle from './TruncatedTitle.vue';

export default defineComponent({
  components: {
    Comments,
    TruncatedTitle
  },
  props: {
    title: String,
    detail: String
  },
  setup(props, { emit }) {
    const { deleteBlog } = useDelete();
    const { editBlog } = useEdit();

    return { 
      deleteBlog, 
      editBlog: () => editBlog(),
      markdownToHtml
    };
  }
});
</script>

<style scoped>
.blog {
  position: relative;
  padding: 20px;
  border: 1px solid #e0e0e0;
  border-radius: 8px;
  flex: 1;
}

.blog-actions {
  position: absolute;
  top: 10px;
  right: 10px;
}

.blog-title {
  font-size: 24px;
  max-width: 300px;
  width: fit-content;
}

.delete-btn, .edit-btn {
  margin-left: 10px;
  padding: 5px 10px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

.delete-btn {
  background-color: #f44336;
  color: white;
}

.edit-btn {
  background-color: #2196F3;
  color: white;
}
</style>

// projects/svelte/src/components/Blog.svelte
<!-- 
Copyright (c) 2025 Bytedance Ltd. and/or its affiliates

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 -->

<script lang="ts">
  import { blogs, selectedBlog } from '../stores/blogStore';
  import { comments } from '../stores/commentStore';
  import { parseMarkdown } from '../utils/markdown';
  import Comments from './Comments.svelte';
  import TruncatedTitle from './TruncatedTitle.svelte';
  
  export let title: string;
  export let detail: string;
  export let onEdit: () => void;

  $: parsedDetail = parseMarkdown(detail);

  function handleDelete() {
    blogs.deleteBlog(title);
    comments.deleteBlogComments(title);
    const firstBlog = $blogs[0];
    if(firstBlog) {
      selectedBlog.set(firstBlog);
    } else {
      selectedBlog.set({title: '', detail: ''});
    }
  }
</script>

{#if title && detail}
  <div>
    <div class="blog-header">
      <h2 class="blog-title">
        <TruncatedTitle title={title} maxWidth={400} />
      </h2>
      <div class="button-group">
        <button class="edit-btn" on:click={onEdit}>Edit</button>
        <button class="delete-btn" on:click={handleDelete}>Delete</button>
      </div>
    </div>
    <div class="blog-content">
      {@html parsedDetail}
    </div>
    <Comments blogTitle={title} />
  </div>
{/if}

<style>
  .blog-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
  }

  .blog-title {
    width: fit-content;
    font-size: 24px;
  }

  .button-group {
    display: flex;
    gap: 8px;
  }

  .delete-btn {
    background-color: #dc3545;
    color: white;
    border: none;
    padding: 0.5rem 1rem;
    border-radius: 4px;
    cursor: pointer;
    font-size: 1rem;
    transition: background-color 0.2s;
  }

  .delete-btn:hover {
    background-color: #c82333;
  }

  .edit-btn {
    background-color: #007bff;
    color: white;
    border: none;
    padding: 0.5rem 1rem;
    border-radius: 4px;
    cursor: pointer;
    font-size: 1rem;
    transition: background-color 0.2s;
  }

  .edit-btn:hover {
    background-color: #0056b3;
  }

  .blog-content :global(h1) {
    font-size: 2em;
    margin: 0.67em 0;
  }

  .blog-content :global(h2) {
    font-size: 1.5em;
    margin: 0.83em 0;
  }

  .blog-content :global(h3) {
    font-size: 1.17em;
    margin: 1em 0;
  }

  .blog-content :global(p) {
    margin: 1em 0;
  }

  .blog-content :global(ul) {
    margin: 1em 0;
    padding-left: 40px;
  }

  .blog-content :global(code) {
    background-color: #f5f5f5;
    padding: 0.2em 0.4em;
    border-radius: 3px;
    font-family: monospace;
  }

  .blog-content :global(a) {
    color: #007bff;
    text-decoration: none;
  }

  .blog-content :global(a:hover) {
    text-decoration: underline;
  }
</style>
